### ISSUE TITLE
Any new Progress about the project

### ISSUE THREAD

**Issue by chengwei0427** [HaisenbergPeng/ROLL#1]
Hi, @HaisenbergPeng 

Any new Progress about the project?

**Comment by ibrahimhroob** [comment]
hey @HaisenbergPeng , thanks for the nice work, has the paper been accepted? and when the code will be available? thanks

**Comment by HaisenbergPeng** [comment]
Hi guys! Thanks for your interest, gladly the paper is now accepted! The code will be released in the coming week.

**Comment by ibrahimhroob** [comment]
Wohoo, congrats 🎉
